# Generated by Django 4.1.1 on 2022-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="Email address"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="First name"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Last name"
            ),
        ),
    ]
