# Generated by Django 4.1.1 on 2022-10-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_alter_machinemodel_machine_type"),
        ("accounts", "0003_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="catalogue.part",
            ),
        ),
    ]
