# Generated by Django 4.1.1 on 2022-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_email_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="/empty_avatar.png",
                null=True,
                upload_to="profiles_avatars/%Y/%m/%d/",
                verbose_name="Avatar",
            ),
        ),
    ]
