# Generated by Django 4.1.1 on 2022-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/part_photos/empty_part_image.png",
                null=True,
                upload_to="part_photos/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
    ]
