# Generated by Django 4.1.1 on 2022-09-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="cart",
        ),
        migrations.AlterField(
            model_name="machinemodel",
            name="part",
            field=models.ManyToManyField(related_name="machine_model", to="catalogue.part"),
        ),
        migrations.AlterField(
            model_name="part",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part",
                to="core.shop",
            ),
        ),
    ]
