# Generated by Django 4.1.1 on 2022-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="machine_system",
            field=models.IntegerField(
                choices=[
                    (1, "Engine"),
                    (2, "Transmission"),
                    (3, "Hydraulic"),
                    (4, "Steering and brake"),
                    (5, "Electric"),
                    (6, "Electronic"),
                    (7, "Chassis"),
                ],
                default=1,
                verbose_name="Machine type",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/part_photos/blank.png",
                null=True,
                upload_to="part_photos/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
    ]
