# Generated by Django 4.1.1 on 2022-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_part_machine_system_alter_part_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="remark",
        ),
        migrations.AddField(
            model_name="part",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
