# Generated by Django 4.1.1 on 2022-09-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_cart_parts"),
        ("catalogue", "0003_part_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinemodel",
            name="machine_type",
            field=models.IntegerField(
                choices=[
                    (1, "Tractor"),
                    (2, "Combine"),
                    (3, "Self-propelled sprayer"),
                    (4, "Self-propelled forage combine"),
                    (5, "Loader"),
                ],
                default="Please choose a machine type",
                max_length=50,
                verbose_name="Machine type",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="part",
                to="cart.cart",
            ),
        ),
    ]
