# Generated by Django 4.1.1 on 2022-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0005_alter_machinemodel_machine_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="shop",
        ),
        migrations.AlterField(
            model_name="part",
            name="part_name",
            field=models.CharField(max_length=125, null=True, verbose_name="Part name"),
        ),
    ]
