# Generated by Django 4.1.1 on 2022-10-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0007_alter_part_part_number_alter_part_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machinemodel",
            name="machine_type",
            field=models.IntegerField(
                choices=[
                    (1, "Tractor"),
                    (2, "Combine"),
                    (3, "Self-propelled sprayer"),
                    (4, "Self-propelled forage combine"),
                    (5, "Loader"),
                ],
                default=1,
                verbose_name="Machine type",
            ),
        ),
    ]
