# Generated by Django 4.1.1 on 2022-10-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_alter_machinemodel_machine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="stock_quantity",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
