# Generated by Django 4.1.1 on 2022-10-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0009_part_stock_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="cart",
        ),
    ]
