# Generated by Django 4.1.1 on 2022-09-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0006_remove_part_shop_alter_part_part_name"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="part",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop",
                to="catalogue.part",
            ),
        ),
    ]
