# Generated by Django 4.1.1 on 2022-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="location1",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
