# Generated by Django 4.1.1 on 2022-10-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0008_alter_machinemodel_machine_type"),
        ("core", "0002_shop_part"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="part",
        ),
        migrations.AddField(
            model_name="shop",
            name="part",
            field=models.ManyToManyField(
                null=True, related_name="shop", to="catalogue.part"
            ),
        ),
    ]
