# Generated by Django 4.1.1 on 2022-10-24 15:09

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_shop_location1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="location1",
        ),
        migrations.AddField(
            model_name="shop",
            name="location",
            field=location_field.models.plain.PlainLocationField(
                max_length=63, null=True
            ),
        ),
    ]
