# Generated by Django 4.1.1 on 2022-11-15 19:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="city",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="contact_name",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="contact_surname",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="delivery_service",
            field=models.IntegerField(
                choices=[
                    (1, "Nova Poshta"),
                    (2, "Meest Express"),
                    (3, "Ukrposhta"),
                    (4, "Self-delivery"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Contact phone number",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="payment_type",
            field=models.IntegerField(
                choices=[(1, "GooglePay"), (2, "Visa"), (3, "Cash")], default=1
            ),
        ),
    ]
