# Generated by Django 4.1.1 on 2022-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="payment_id",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
