# Generated by Django 4.1.1 on 2022-11-15 19:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_city_cart_contact_name_cart_contact_surname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="contact_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="contact_surname",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
    ]
