# Generated by Django 4.1.1 on 2022-11-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cartitem_part"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="discount_price",
            new_name="discount",
        ),
    ]
