# Generated by Django 4.1.1 on 2022-09-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_parts_ordershistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="parts",
        ),
    ]
