# Generated by Django 4.1.1 on 2022-11-11 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="orders_history",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart",
                to="cart.ordershistory",
            ),
        ),
    ]
