# Generated by Django 4.1.1 on 2022-10-06 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0006_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordershistory",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
