# Generated by Django 4.1.1 on 2022-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_cart_payment_type_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="payment_type",
            field=models.CharField(
                choices=[(1, "GooglePay"), (2, "Visa"), (3, "PayPal")],
                default="Visa",
                max_length=100,
            ),
        ),
    ]
