# Generated by Django 4.1.1 on 2022-10-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_cart_payment_type"),
        ("cart", "0009_alter_cartitem_cart"),
    ]

    operations = []
