# Generated by Django 4.1.1 on 2022-10-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0011_alter_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordershistory",
            name="cart",
        ),
        migrations.AddField(
            model_name="cart",
            name="orders_history",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="cart.ordershistory",
            ),
        ),
    ]
