# Generated by Django 4.1.1 on 2022-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0012_remove_ordershistory_cart_cart_orders_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="payment_type",
            field=models.IntegerField(
                choices=[(1, "GooglePay"), (2, "Visa"), (3, "PayPal")],
                default="Visa",
                max_length=100,
            ),
        ),
    ]
